name: Build and Deploy to Azure

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub e build da imagem
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}:latest .
          docker push ${{ secrets.DOCKER_REPO }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy para o Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: susp-app-prd
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          images: ${{ secrets.DOCKER_REPO }}:latest
