name: Cria imagem Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build do projeto com Maven
        working-directory: seguranca
        run: mvn clean package -DskipTests

      - name: Login no Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .

      - name: Push da imagem Docker para o Docker Hub
        run: docker push ${{ secrets.DOCKER_REPO }}:latest

    deploy:
      name: Deploy to Azure
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
            publish-profile: |
              {
                "publishUrl": "https://${{ secrets.AZURE_WEBAPP_NAME }}.scm.azurewebsites.net",
                "userName": "${{ secrets.AZURE_USERNAME }}",
                "userPWD": "${{ secrets.AZURE_PASSWORD }}",
                "destinationAppUrl": "https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net"
              }
            images: '${{ secrets.DOCKER_USERNAME }}/suspapp:latest'