name: CI/CD - Produção

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build do projeto com Maven
        working-directory: seguranca
        run: mvn clean package -DskipTests

      - name: Login no Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .

      - name: Push da imagem Docker para o Docker Hub
        run: docker push ${{ secrets.DOCKER_REPO }}:latest

